# Generated by Django 4.1.7 on 2023-07-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'کارت', 'verbose_name_plural': 'کارت ها'},
        ),
    ]
