# Generated by Django 4.2.3 on 2023-07-30 13:29

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_alter_cartitem_quantity_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to='shop/images', validators=[shop.validators.file_size_validation], verbose_name='تصویر دسته'),
        ),
    ]
