# Generated by Django 4.2.3 on 2023-08-04 14:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_custom_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1, validators=[core.validators.validate_phone_number], verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
