# Generated by Django 4.2.3 on 2023-08-04 16:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[core.validators.validate_phone_number], verbose_name='شماره تلفن'),
        ),
    ]
